# syntax=docker/dockerfile:1

# Multi-stage build for Next.js standalone output.
#
# Stages are split so that a source-only change reuses the cached dependency
# layer: package files are copied and installed before the rest of the tree.

ARG NODE_VERSION=22-alpine

# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS base
# Next's precompiled binaries expect glibc symbols that musl doesn't provide.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# --- dependencies ----------------------------------------------------------
FROM base AS deps
# Only the manifests, so this layer is invalidated by dependency changes alone.
COPY package.json package-lock.json ./
RUN npm ci

# --- build -----------------------------------------------------------------
FROM base AS builder
ENV NEXT_TELEMETRY_DISABLED=1

# NEXT_PUBLIC_* values are inlined into the client bundle during the build, so
# this has to be present here rather than at container start. Left unset, the
# app falls back to http://localhost:3000 for metadata URLs.
ARG NEXT_PUBLIC_SITE_URL=""
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# --- runtime ---------------------------------------------------------------
FROM base AS runner

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Run as an unprivileged user. Never the root the base image defaults to.
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 --ingroup nodejs nextjs

# public/ is served by the standalone server but isn't part of its trace.
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1

# server.js is generated by `output: "standalone"`.
CMD ["node", "server.js"]
